### ISSUE TITLE
Exception with original unmodified last commit

### ISSUE THREAD

**Issue by gravitstudio** [Sameera-Perera/Flutter-TDD-Clean-Architecture-E-Commerce-App#5]
Hi friend, in the last commit I tried to compile app, all work instead this: in phase of buy after press confirm button, compiler show an exception in the attached image

![Screenshot 2023-10-14 160618](https://github.com/Sameera-Perera/Flutter-TDD-Clean-Architecture-E-Commerce-App/assets/25841991/7b29dce6-12d8-4ce6-b983-19ab90848b20)

**Comment by Sameera-Perera** [comment]
Thank you for reporting this issue, Emiliano.
It seems like the 'deliveryInformation' list is empty, causing an exception when trying to access the first element in this list.

In the current development phase, I'm implementing a feature to select specific delivery information from the 'deliveryInformation' list, which can be found in the [feature/delivery-info](https://github.com/Sameera-Perera/Flutter-TDD-Clean-Architecture-E-Commerce-App/tree/feature/delivery-info),  Once a specific delivery information item is selected from this list, it will be passed as the 'selectedDeliveryInformation' object, replacing the use of 'deliveryInformation.first' and should show proper massage if `selectedDeliveryInformation` is `null`. By the end of this feature development this issue will be fixed.

**Comment by gravitstudio** [comment]
Thank you Sameera, so far it's a good code app, I study it. good job

Emi

**Comment by Sameera-Perera** [comment]
Fixed. Release v1.0.9.
